[package]
name = 'fio'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'fio'

[dependencies]
extendr-api = '*'
faer = { version = '*', features = ['rayon'] }
rayon = '*'
num_cpus = '*'
